---

- name: "Update cache"
  apt:
    update_cache: "{{ update_cache }}"
    cache_valid_time: "{{ cache_valid_time }}"

- name: "Install Postgresql 10"
  apt:
    name: postgresql-10
    state: present

- name: "Create user, set password, grant privs"
  become_user: postgres
  become: "yes"
  postgresql_user:
    name: redmine
    password: minered
    expires: 'infinity'
    role_attr_flags: CREATEDB,NOSUPERUSER
  no_log: true

- name: "Create a new database with name redmine"
  become_user: postgres
  become: "yes"
  postgresql_db:
    name: redmine
    owner: redmine
    encoding: UTF-8
