---

- name: "Update cache"
  apt:
    update_cache: "{{ update_cache }}"
    cache_valid_time: "{{ cache_valid_time }}"

- name: "Install Postgresql 10"
  apt:
    name: postgresql-10
    state: present

- name: "Create user, set password, grant privs"
  become_user: postgres
  become: "yes"
  postgresql_user:
    name: "{{ item.value.settings.0.params.db }}"
    password: "{{ item.value.settings.0.params.db_pass }}"
    expires: 'infinity'
    role_attr_flags: CREATEDB,NOSUPERUSER
  no_log: true
  loop: "{{ lookup('dict', group_dict ) }}"

- name: "Create a new database with name redmine"
  become_user: postgres
  become: "yes"
  postgresql_db:
    name: "{{ item.value.settings.0.params.db }}"
    owner: "{{ item.value.settings.0.params.db }}"
    encoding: UTF-8
  loop: "{{ lookup('dict', group_dict ) }}"
