---

- hosts: redmine_host
  remote_user: deploy
  become: "yes"
  become_user: "root"
  become_method: "sudo"
  gather_facts: true

  vars:
    servername: "{{ inventory_hostname }}"

    # role: addusers
    path_to_mount_raid: /raid
    group_dict:
      private:
        settings:
          - name: app1
            params:
              mode: "u=rwx,g=rwx,o=---"
              owner: nobody
              folder_state: directory
              grp_state: present
              acl_state: present
              port: 9393
              db: db_app1
              db_pass: "Tushoo7e"
              path: /raid/
              group: app1
      public:
        settings:
          - name: app2
            params:
              mode: "u=rwx,g=rwx,o=---"
              owner: nobody
              folder_state: directory
              grp_state: present
              acl_state: present
              port: 9393
              db: db_app2
              db_pass: "Tee0AeKa"
              path: /raid/
              group: app1
    users:
      user1:
        description: "User firstname and surname"
        password: "tuphee9H"
        state: present
        grps:
          - app1
      user2:
        description: "User firstname and surname"
        password: "heewai0A"
        state: present
        grps:
          - app1
          - app2

    # role: redmine
    av_user:
      - user1
      - user2

    # role: geerlingguy.ruby
    workspace: /root
    ruby_version: 2.5.1
    ruby_install_bundler: true
    ruby_install_gems_user: deploy

  roles:
    - {role: info, tags: 'info'}
    - {role: common, tags: 'common'}
    - {role: addusers, tags: 'addusers'}
    - {role: postgresql, tags: 'postgresql'}
    - {role: geerlingguy.ruby, tags: 'ruby'}
    - {role: redmine, tags: 'redmine'}
    - {role: puma_service, tags: 'puma'}
