---

- hosts: redmine
  remote_user: deploy
  become: "yes"
  become_user: "root"
  become_method: "sudo"
  gather_facts: true

  vars:
    servername: "{{ inventory_hostname }}"

# role: zzet.rbenv
    rbenv:
      env: system
      version: v1.1.2
      default_ruby: 2.6.6
      rubies:
        - version: 2.6.6
    rbenv_clean_up: "false"
    rbenv_users: 
      - user1
      - user2

# role: addusers
    path_to_mount_raid: /raid
    group_dict:
      private:
        settings:
          - name: app1
            params:
              mode: "u=rwx,g=rwx,o---"
              owner: nobody
              folder_state: directory
              grp_state: present
              acl_state: present
      public:
        settings:
          - name: app2
            params:
              mode: "u=rwx,g=rwx,o---"
              owner: nobody
              folder_state: directory
              grp_state: present
              acl_state: present
    users:
      user1:
        description: "User firstname and surname"
        password: "tuphee9H"
        state: present
        grps:
          - app1
      user2:
        description: "User firstname and surname"
        password: "heewai0A"
        state: present
        grps:
          - app1
          - app2

# role: gems
    av_user:
      - user1
      - user2

# role: geerlingguy.ruby
    ruby_install_bundler: true
    
  roles:
    - { role: info, tags: 'info' }
    - { role: common, tags: 'common' }
    - { role: addusers, tags: 'addusers' }
    - { role: zzet.rbenv, tags: 'rbenv' }
    - { role: geerlingguy.ruby, tags: 'bundler' }
    - { role: gems, tags: 'gems' }
    - { role: redmine, tags: 'redmine' }

