---

- name: "Template .gemrc to {{ item }} directory"
  template:
    src: "templates/.gemrc.j2"
    dest: "{{ path_to_mount_raid }}/users_private/{{ item }}/.gemrc"
    owner: "{{ item }}"
    group: "{{ item }}"
    mode: '0600'
  loop: "{{ av_user }}"

- name: "Clone redmine's repo"
  git:
    repo: "https://github.com/redmine/redmine"
    dest: "{{ path_to_mount_raid }}/{{ item.1.name }}"
  loop: "{{ group_dict | dict2items | subelements('value.settings') }}"

- name: "Install dependencies"
  apt:
    pkg:
      - imagemagick
      - ghostscript

- name: "DEBUG!"
  debug:
    msg: "{{ path_to_mount_raid }}/{{ item.1.name }}/Gemfile"
  loop: "{{ group_dict | dict2items | subelements('value.settings') }}"
  tags: test

- name: "Install gems"
  bundler:
    state: present
    gemfile: "{{ path_to_mount_raid }}/{{ item.1.name }}/Gemfile"
    extra_args: --without development test
  loop: "{{ group_dict | dict2items | subelements('value.settings') }}"
