---

- name: "Template .gemrc to {{ item }} directory"
  template:
    src: "templates/.gemrc.j2"
    dest: "{{ path_to_mount_raid }}/users_private/{{ item }}/.gemrc"
    owner: "{{ item }}"
    group: "{{ item }}"
    mode: '0600'
  loop: "{{ av_user }}"

- name: "Clone redmine's repo"
  git:
    repo: "https://github.com/redmine/redmine"
    dest: "{{ path_to_mount_raid }}/{{ item.1.name }}"
  loop: "{{ group_dict | dict2items | subelements('value.settings') }}"

- name: "Give user permissions"
  file:
    path: "{{ path_to_mount_raid }}/{{ item.1.name }}"
    owner: "{{ item.1.params.owner }}"
    group: "{{ item.1.name }}"
    recurse: "yes"
  loop: "{{ group_dict | dict2items | subelements('value.settings') }}"

- name: "Install dependencies"
  apt:
    pkg:
      - imagemagick
      - ghostscript
      - zlib1g-dev
      - libpq-dev

- name: "Install gems from Gemfile"
  bundler:
    state: present
    user_install: "no"
    exclude_groups:
      - development
      - test
    gemfile: "{{ path_to_mount_raid }}/{{ item.1.name }}/Gemfile"
  loop: "{{ group_dict | dict2items | subelements('value.settings') }}"

- bundler:
    state: latest
    chdir: /raid/app1
  tags: g1

- name: "Install gems from list"
  gem:
    name: "{{ item.name }}"
    version: "{{ item.ver }}"
    user_install: "no"
    state: present
  loop:
    - { name: 'pg', ver: '1.2.3' }
    - { name: 'rake', ver: '11.2.2' }
#    - { name: 'ast', ver: '2.4.1' }
#    - { name: 'regexp_parser', ver: '1.7.1' }
#    - { name: 'xpath', ver: '3.2.0' }
#    - { name: 'capybara', ver: '3.31.0' }
#    - { name: 'childprocess', ver: '3.0.0' }
#    - { name: 'docile', ver: '1.3.2' }
#    - { name: 'jaro_winkler', ver: '1.5.4' }
#    - { name: 'mocha', ver: '1.11.2' }
#    - { name: 'parallel', ver: '1.19.2' }
#    - { name: 'parser', ver: '2.7.1.4' }
#    - { name: 'puma', ver: '4.3.5' }
#    - { name: 'rainbow', ver: '3.0.0' }
#    - { name: 'rexml', ver: '3.2.4' }
#    - { name: 'ruby-progressbar', ver: '1.10.1' }
#    - { name: 'unicode-display_width', ver: '1.7.0' }
    - { name: 'rubocop', ver: '0.81.0' }
