---

- name: "Template .gemrc to {{ item }} directory"
  template:
    src: "templates/.gemrc.j2"
    dest: "{{ path_to_mount_raid }}/users_private/{{ item }}/.gemrc"
    owner: "{{ item }}"
    group: "{{ item }}"
    mode: '0600'
  loop: "{{ av_user }}"

- name: "Clone redmine's repo"
  git:
    repo: "https://github.com/redmine/redmine"
    dest: "{{ path_to_mount_raid }}/{{ item.1.name }}"
  loop: "{{ group_dict | dict2items | subelements('value.settings') }}"

- name: "Give user permissions"
  file:
    path: "{{ path_to_mount_raid }}/{{ item.1.name }}"
    owner: "{{ item.1.params.owner }}"
    group: "{{ item.1.name }}"
    recurse: "yes"
  loop: "{{ group_dict | dict2items | subelements('value.settings') }}"

- name: "Install dependencies"
  apt:
    pkg:
      - imagemagick
      - ghostscript
      - zlib1g-dev
      - libpq-dev

- name: "Template postgresql config"
  template:
    src: "roles/redmine/templates/database.yml.j2"
    dest: "{{ path_to_mount_raid }}/{{ item.value.settings.0.name }}/config/database.yml"
    group: "{{ item.value.settings.0.params.group }}"
    mode: '0770'
  loop: "{{ lookup('dict', group_dict) }}"

- name: "Install gems from Gemfile"
  bundler:
    state: present
    user_install: "no"
    chdir: "{{ path_to_mount_raid }}/{{ item.1.name }}"
  loop: "{{ group_dict | dict2items | subelements('value.settings') }}"

- name: "Generate the secret token"
  command: "bundle exec rake generate_secret_token"
  args:
    chdir: "{{ path_to_mount_raid }}/{{ item.1.name }}"
  run_once: "true"
  loop: "{{ group_dict | dict2items | subelements('value.settings') }}"

- name: "Run the database migrations"
  command: "bundle exec rake db:migrate"
  args:
    chdir: "{{ path_to_mount_raid }}/{{ item.1.name }}"
  environment:
    RAILS_ENV: production
  run_once: "true"
  loop: "{{ group_dict | dict2items | subelements('value.settings') }}"

- name: "Run load default data"
  become_user: "{{ item.0.key }}"
  expect:
    command: "bundle exec rake redmine:load_default_data"
    timeout: 5
    responses:
      Select language(.*): 'en'
  args:
    chdir: "{{ path_to_mount_raid }}/{{ item.1 }}"
  environment:
    RAILS_ENV: production
  run_once: "true"
  loop: "{{ users | dict2items | subelements('value.grps') }}"
  no_log: true
