---

- name: "Create groups"
  group:
    name: "{{ item.1.name }}"
    state: "{{ item.1.params.grp_state }}"
  loop: "{{ group_dict | dict2items | subelements('value.settings') }}"

- name: "Create folders"
  file:
    path: "{{ path_to_mount_raid }}/{{ item.1.name }}"
    owner: "{{ item.1.params.owner }}"
    group: "{{ item.1.name }}"
    mode: "{{ item.1.params.mode }}"
    state: "{{ item.1.params.folder_state }}"
  loop: "{{ group_dict | dict2items | subelements('value.settings') }}"

- name: "Create users"
  user:
    name: "{{ item.key }}"
    comment: "{{ item.value.description }}"
    shell: /bin/bash
    groups: "{{ item.value.grps | list }}"
    home: "{{ path_to_mount_raid }}/users_private/{{ item.key }}"
    state: "{{ item.value.state }}"
    expires: 1422403387
  loop: "{{ lookup('dict', users) }}"

- name: "Sets default ACL"
  acl:
    path: "{{ path_to_mount_raid }}/{{ item.1.name }}"
    entity: "{{ item.1.name }}"
    etype: group
    permissions: rw
    default: "yes"
    state: "{{ item.1.params.acl_state }}"
  loop: "{{ group_dict | dict2items | subelements('value.settings') }}"
  when: item.1.params.acl_state == "present"
