---

- name: "Push template puma.rb"
  template:
    src: "templates/puma.rb.j2"
    dest: "{{ item.value.settings.0.params.path }}/
    {{ item.value.settings.0.name }}/config/puma.rb"
    owner: "{{ item.value.settings.0.params.owner }}"
    group: "{{ item.value.settings.0.params.group }}"
    mode: '0640'
  loop: "{{ lookup('dict', group_dict) }}"

- name: "Create a directory for service file"
  become_user: "{{ item.key }}"
  become: "yes"
  file:
    path: "{{ path_to_mount_raid }}/users_private/
    {{ item.key }}/.config/systemd/user"
    state: directory
    mode: '0700'
  loop: "{{ lookup('dict', users) }}"

- name: "Push systemd service template"
  template:
    src: "templates/puma.service.j2"
    dest: "{{ item.value.settings.0.params.path }}/users_private/{{ item.value.settings.0.params.owner }}/.config/systemd/user/puma.service"
    owner: "{{ item.value.settings.0.params.owner }}"
    group: "{{ item.value.settings.0.params.group }}"
    mode: '0640'
  loop: "{{ lookup('dict', group_dict) }}"
  tags: go

- debug:
    msg: "{{ item.value.settings.0.params.owner }}"
  loop: "{{ lookup('dict', group_dict) }}"
