---

- name: "Push template puma.rb"
  template:
    src: "templates/puma.rb.j2"
    dest: "{{ item.value.settings.0.params.path }}/\
    {{ item.value.settings.0.name }}/config/puma.rb"
    owner: "{{ item.value.settings.0.params.owner }}"
    group: "{{ item.value.settings.0.params.group }}"
    mode: '0640'
  loop: "{{ lookup('dict', group_dict) }}"

- name: "Create the directory for service file"
  become_user: "{{ item[1].key }}"
  become: "yes"
  file:
    path: "{{ item[0].value.settings.0.params.path }}/users_private/\
    {{ item[1].key }}/.config/systemd/user"
    state: directory
    mode: '0700'
  with_nested:
    - "{{ lookup('dict', group_dict) }}"
    - "{{ lookup('dict', users) }}"

- name: "Push systemd service template"
  template:
    src: "templates/puma.service.j2"
    dest: "{{ item.value.settings.0.params.path }}/users_private/\
    {{ item.value.settings.0.params.owner }}/.config/systemd/user/puma.service"
    owner: "{{ item.value.settings.0.params.owner }}"
    group: "{{ item.value.settings.0.params.group }}"
    mode: '0700'
  loop: "{{ lookup('dict', group_dict) }}"

- name: "Touch .profile"
  file:
    path: "{{ item.value.settings.0.params.path }}/users_private/\
      {{ item.value.settings.0.params.owner }}/.profile"
    owner: "{{ item.value.settings.0.params.owner }}"
    state: touch
    mode: '0700'
  loop: "{{ lookup('dict', group_dict) }}"

- name: "Use wrapper of getent for check user uid"
  getent:
    database: passwd

- name: "Insert env to .profile"
  lineinfile:
    dest: "{{ item.value.settings.0.params.path }}/users_private/\
    {{ item.value.settings.0.params.owner }}/.profile"
    insertafter: "^fi$"
    line: "export XDG_RUNTIME_DIR=/run/user/\
    {{ getent_passwd[item.value.settings.0.params.owner].1 }}"
  loop: "{{ lookup('dict', group_dict) }}"

- name: "Create the directory for linger"
  file:
    path: "/var/lib/systemd/linger"
    state: directory
    mode: '755'

- name: "Touch user linger file"
  file:
    path: "/var/lib/systemd/linger/{{ item.value.settings.0.params.owner }}"
    owner: "{{ item.value.settings.0.params.owner }}"
    state: touch
    mode: '644'
  loop: "{{ lookup('dict', group_dict) }}"

- name: "Start enable-linger for users"
  command: "loginctl enable-linger {{ item.value.settings.0.params.owner }}"
  loop: "{{ lookup('dict', group_dict) }}"

- name: "Start puma services"
  become: "yes"
  become_user: "{{ item.value.settings.0.params.owner }}"
  systemd:
    daemon_reload: "yes"
    enabled: "yes"
    scope: user
    state: started
    name: puma.service
  environment:
    XDG_RUNTIME_DIR: "/run/user/\
    {{ getent_passwd[item.value.settings.0.params.owner].1 }}"
  loop: "{{ lookup('dict', group_dict) }}"
